import java.io.IOException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author usuario
 */
public class Practica3 extends javax.swing.JFrame {
    /**
     * Creates new form Practica3
     */
    public Practica3() {
        initComponents();
        jToggleButton1.setEnabled(false);
        jToggleButton2.setEnabled(false);
        jToggleButton3.setEnabled(false);
        jToggleButton4.setEnabled(false);
        jToggleButton5.setEnabled(false);
        jToggleButton6.setEnabled(false);
        jToggleButton7.setEnabled(false);
        jToggleButton8.setEnabled(false);
        jToggleButton9.setEnabled(false);
        jToggleButton10.setEnabled(false);
        jToggleButton11.setEnabled(false);
        jToggleButton12.setEnabled(false);
        jToggleButton13.setEnabled(false);
        jToggleButton14.setEnabled(false);
        jToggleButton15.setEnabled(false);
        jToggleButton16.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton9 = new javax.swing.JToggleButton();
        jToggleButton10 = new javax.swing.JToggleButton();
        jToggleButton11 = new javax.swing.JToggleButton();
        jToggleButton12 = new javax.swing.JToggleButton();
        jToggleButton13 = new javax.swing.JToggleButton();
        jToggleButton14 = new javax.swing.JToggleButton();
        jToggleButton15 = new javax.swing.JToggleButton();
        jToggleButton16 = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N

        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N

        jToggleButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N

        jToggleButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N

        jToggleButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N

        jToggleButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N

        jToggleButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N

        jToggleButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N

        jToggleButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N

        jToggleButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N

        jToggleButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N

        jToggleButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N

        jToggleButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N

        jToggleButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N

        jToggleButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N

        jToggleButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Z.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jToggleButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jToggleButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton8))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jToggleButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton12))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jToggleButton13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton16)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton4)
                    .addComponent(jToggleButton3)
                    .addComponent(jToggleButton2)
                    .addComponent(jToggleButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton5)
                    .addComponent(jToggleButton6)
                    .addComponent(jToggleButton7)
                    .addComponent(jToggleButton8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton9)
                    .addComponent(jToggleButton10)
                    .addComponent(jToggleButton11)
                    .addComponent(jToggleButton12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton13)
                    .addComponent(jToggleButton14)
                    .addComponent(jToggleButton15)
                    .addComponent(jToggleButton16))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setText("Empezar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Recordar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Comprobar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Aciertos");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jLabel9.setText("");
        
        Random generadorNum = new Random();
        String numeroGenerado = "";
        String enlace = "";
        int contador;

        for (contador = 0; contador <= 4; contador++) {
            numeroGenerado += (char) ('A' + generadorNum.nextInt(15));

            for (contador = 0; contador < numeroGenerado.length(); contador++) {
                enlace = "/imagenes/" + numeroGenerado.charAt(contador) + ".png";
                if (contador == 0) {
                    try {
                        jLabel1.setIcon(new ImageIcon(ImageIO.read(getClass().getResource(enlace))));
                    } catch (IOException ex) {
                        Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                if (contador == 1) {
                    try {
                        jLabel2.setIcon(new ImageIcon(ImageIO.read(getClass().getResource(enlace))));
                    } catch (IOException ex) {
                        Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                if (contador == 2) {
                    try {
                        jLabel3.setIcon(new ImageIcon(ImageIO.read(getClass().getResource(enlace))));
                    } catch (IOException ex) {
                        Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                if (contador == 3) {
                    try {
                        jLabel4.setIcon(new ImageIcon(ImageIO.read(getClass().getResource(enlace))));
                    } catch (IOException ex) {
                        Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jToggleButton1.setEnabled(true);
        jToggleButton2.setEnabled(true);
        jToggleButton3.setEnabled(true);
        jToggleButton4.setEnabled(true);
        jToggleButton5.setEnabled(true);
        jToggleButton6.setEnabled(true);
        jToggleButton7.setEnabled(true);
        jToggleButton8.setEnabled(true);
        jToggleButton9.setEnabled(true);
        jToggleButton10.setEnabled(true);
        jToggleButton11.setEnabled(true);
        jToggleButton12.setEnabled(true);
        jToggleButton13.setEnabled(true);
        jToggleButton14.setEnabled(true);
        jToggleButton15.setEnabled(true);
        jToggleButton16.setEnabled(true);
        
        try {
            jLabel1.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/Z.png"))));
        } catch (IOException ex) {
            Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            jLabel2.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/Z.png"))));
        } catch (IOException ex) {
            Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            jLabel3.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/Z.png"))));
        } catch (IOException ex) {
            Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            jLabel4.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/imagenes/Z.png"))));
        } catch (IOException ex) {
            Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Random generadorNum = new Random();
        String numeroGenerado = "";
        String enlace = "";
        int contador;

        for (contador = 0; contador <= 16; contador++) {
            numeroGenerado += (char) ('A' + generadorNum.nextInt(15));

            for (contador = 0; contador < numeroGenerado.length(); contador++) {
                enlace = "/imagenes/" + numeroGenerado.charAt(contador) + ".png";
                if (contador == 0) {
                    try {
                        jToggleButton1.setIcon(new ImageIcon(ImageIO.read(getClass().getResource(enlace))));
                    } catch (IOException ex) {
                        Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                if (contador == 1) {
                    try {
                        jToggleButton2.setIcon(new ImageIcon(ImageIO.read(getClass().getResource(enlace))));
                    } catch (IOException ex) {
                        Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                if (contador == 2) {
                    try {
                        jToggleButton3.setIcon(new ImageIcon(ImageIO.read(getClass().getResource(enlace))));
                    } catch (IOException ex) {
                        Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                if (contador == 3) {
                    try {
                        jToggleButton4.setIcon(new ImageIcon(ImageIO.read(getClass().getResource(enlace))));
                    } catch (IOException ex) {
                        Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                if (contador == 4) {
                    try {
                        jToggleButton5.setIcon(new ImageIcon(ImageIO.read(getClass().getResource(enlace))));
                    } catch (IOException ex) {
                        Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                if (contador == 5) {
                    try {
                        jToggleButton6.setIcon(new ImageIcon(ImageIO.read(getClass().getResource(enlace))));
                    } catch (IOException ex) {
                        Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                if (contador == 6) {
                    try {
                        jToggleButton7.setIcon(new ImageIcon(ImageIO.read(getClass().getResource(enlace))));
                    } catch (IOException ex) {
                        Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                if (contador == 7) {
                    try {
                        jToggleButton8.setIcon(new ImageIcon(ImageIO.read(getClass().getResource(enlace))));
                    } catch (IOException ex) {
                        Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                if (contador == 8) {
                    try {
                        jToggleButton9.setIcon(new ImageIcon(ImageIO.read(getClass().getResource(enlace))));
                    } catch (IOException ex) {
                        Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                if (contador == 9) {
                    try {
                        jToggleButton10.setIcon(new ImageIcon(ImageIO.read(getClass().getResource(enlace))));
                    } catch (IOException ex) {
                        Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                if (contador == 10) {
                    try {
                        jToggleButton11.setIcon(new ImageIcon(ImageIO.read(getClass().getResource(enlace))));
                    } catch (IOException ex) {
                        Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                if (contador == 11) {
                    try {
                        jToggleButton12.setIcon(new ImageIcon(ImageIO.read(getClass().getResource(enlace))));
                    } catch (IOException ex) {
                        Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                if (contador == 12) {
                    try {
                        jToggleButton13.setIcon(new ImageIcon(ImageIO.read(getClass().getResource(enlace))));
                    } catch (IOException ex) {
                        Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                if (contador == 13) {
                    try {
                        jToggleButton14.setIcon(new ImageIcon(ImageIO.read(getClass().getResource(enlace))));
                    } catch (IOException ex) {
                        Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                if (contador == 14) {
                    try {
                        jToggleButton15.setIcon(new ImageIcon(ImageIO.read(getClass().getResource(enlace))));
                    } catch (IOException ex) {
                        Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                if (contador == 15) {
                    try {
                        jToggleButton16.setIcon(new ImageIcon(ImageIO.read(getClass().getResource(enlace))));
                    } catch (IOException ex) {
                        Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int aciertos = 0;
        
        Icon iconoTB1 = jToggleButton1.getIcon();
        Icon iconoTB2 = jToggleButton2.getIcon();
        Icon iconoTB3 = jToggleButton3.getIcon();
        Icon iconoTB4 = jToggleButton4.getIcon();
        Icon iconoTB5 = jToggleButton5.getIcon();
        Icon iconoTB6 = jToggleButton6.getIcon();
        Icon iconoTB7 = jToggleButton7.getIcon();
        Icon iconoTB8 = jToggleButton8.getIcon();
        Icon iconoTB9 = jToggleButton9.getIcon();
        Icon iconoTB10 = jToggleButton10.getIcon();
        Icon iconoTB11 = jToggleButton11.getIcon();
        Icon iconoTB12 = jToggleButton12.getIcon();
        Icon iconoTB13 = jToggleButton13.getIcon();
        Icon iconoTB14 = jToggleButton14.getIcon();
        Icon iconoTB15 = jToggleButton15.getIcon();
        Icon iconoTB16 = jToggleButton16.getIcon();
        Icon iconoL1 = jLabel1.getIcon();
        Icon iconoL2 = jLabel2.getIcon();
        Icon iconoL3 = jLabel3.getIcon();
        Icon iconoL4 = jLabel4.getIcon();
        Icon iconoL5 = jLabel5.getIcon();
        Icon iconoL6 = jLabel6.getIcon();
        Icon iconoL7 = jLabel7.getIcon();
        

        if(iconoTB1 == iconoL1 || iconoTB1 == iconoL2 || iconoTB1 == iconoL3 || iconoTB1 == iconoL4 || iconoTB1 == iconoL5 || iconoTB1 == iconoL6 || iconoTB1 == iconoL7){
            aciertos++;
        }else{
            jToggleButton1.setEnabled(false);
        }
        if(iconoTB2 == iconoL1 || iconoTB2 == iconoL2 || iconoTB2 == iconoL3 || iconoTB2 == iconoL4 || iconoTB1 == iconoL5 || iconoTB1 == iconoL6 || iconoTB1 == iconoL7){
            aciertos++;
        }else{
            jToggleButton2.setEnabled(false);
        }
        if(iconoTB3 == iconoL1 || iconoTB3 == iconoL2 || iconoTB3 == iconoL3 || iconoTB3 == iconoL4 || iconoTB1 == iconoL5 || iconoTB1 == iconoL6 || iconoTB1 == iconoL7){
            aciertos++;
        }else{
            jToggleButton3.setEnabled(false);
        }
        if(iconoTB4 == iconoL1 || iconoTB4 == iconoL2 || iconoTB4 == iconoL3 || iconoTB4 == iconoL4 || iconoTB1 == iconoL5 || iconoTB1 == iconoL6 || iconoTB1 == iconoL7){
            aciertos++;
        }else{
            jToggleButton4.setEnabled(false);
        }
        if(iconoTB5 == iconoL1 || iconoTB5 == iconoL2 || iconoTB5 == iconoL3 || iconoTB5 == iconoL4 || iconoTB1 == iconoL5 || iconoTB1 == iconoL6 || iconoTB1 == iconoL7){
            aciertos++;
        }else{
            jToggleButton5.setEnabled(false);
        }
        if(iconoTB6 == iconoL1 || iconoTB6 == iconoL2 || iconoTB6 == iconoL3 || iconoTB6 == iconoL4 || iconoTB1 == iconoL5 || iconoTB1 == iconoL6 || iconoTB1 == iconoL7){
            aciertos++;
        }else{
            jToggleButton6.setEnabled(false);
        }
        if(iconoTB7 == iconoL1 || iconoTB7 == iconoL2 || iconoTB7 == iconoL3 || iconoTB7 == iconoL4 || iconoTB1 == iconoL5 || iconoTB1 == iconoL6 || iconoTB1 == iconoL7){
            aciertos++;
        }else{
            jToggleButton7.setEnabled(false);
        }
        if(iconoTB8 == iconoL1 || iconoTB8 == iconoL2 || iconoTB8 == iconoL3 || iconoTB8 == iconoL4 || iconoTB1 == iconoL5 || iconoTB1 == iconoL6 || iconoTB1 == iconoL7){
            aciertos++;
        }else{
            jToggleButton8.setEnabled(false);
        }
        if(iconoTB9 == iconoL1 || iconoTB9 == iconoL2 || iconoTB9 == iconoL3 || iconoTB9 == iconoL4 || iconoTB1 == iconoL5 || iconoTB1 == iconoL6 || iconoTB1 == iconoL7){
            aciertos++;
        }else{
            jToggleButton9.setEnabled(false);
        }
        if(iconoTB10 == iconoL1 || iconoTB10 == iconoL2 || iconoTB10 == iconoL3 || iconoTB10 == iconoL4 || iconoTB1 == iconoL5 || iconoTB1 == iconoL6 || iconoTB1 == iconoL7){
            aciertos++;
        }else{
            jToggleButton10.setEnabled(false);
        }
        if(iconoTB11 == iconoL1 || iconoTB11 == iconoL2 || iconoTB11 == iconoL3 || iconoTB11 == iconoL4 || iconoTB1 == iconoL5 || iconoTB1 == iconoL6 || iconoTB1 == iconoL7){
            aciertos++;
        }else{
            jToggleButton11.setEnabled(false);
        }
        if(iconoTB12 == iconoL1 || iconoTB12 == iconoL2 || iconoTB12 == iconoL3 || iconoTB12 == iconoL4 || iconoTB1 == iconoL5 || iconoTB1 == iconoL6 || iconoTB1 == iconoL7){
            aciertos++;
        }else{
            jToggleButton12.setEnabled(false);
        }
        if(iconoTB13 == iconoL1 || iconoTB13 == iconoL2 || iconoTB13 == iconoL3 || iconoTB13 == iconoL4 || iconoTB1 == iconoL5 || iconoTB1 == iconoL6 || iconoTB1 == iconoL7){
            aciertos++;
        }else{
            jToggleButton13.setEnabled(false);
        }
        if(iconoTB14 == iconoL1 || iconoTB14 == iconoL2 || iconoTB14 == iconoL3 || iconoTB14 == iconoL4 || iconoTB1 == iconoL5 || iconoTB1 == iconoL6 || iconoTB1 == iconoL7){
            aciertos++;
        }else{
            jToggleButton14.setEnabled(false);
        }
        if(iconoTB15 == iconoL1 || iconoTB15 == iconoL2 || iconoTB15 == iconoL3 || iconoTB15 == iconoL4 || iconoTB1 == iconoL5 || iconoTB1 == iconoL6 || iconoTB1 == iconoL7){
            aciertos++;
        }else{
            jToggleButton15.setEnabled(false);
        }
        if(iconoTB16 == iconoL1 || iconoTB16 == iconoL2 || iconoTB16 == iconoL3 || iconoTB16 == iconoL4 || iconoTB1 == iconoL5 || iconoTB1 == iconoL6 || iconoTB1 == iconoL7){
            aciertos++;
        }else{
            jToggleButton16.setEnabled(false);
        }
        
        
        
        System.out.println(aciertos);
        
        jLabel9.setText(String.valueOf(aciertos));
        
        
    }//GEN-LAST:event_jButton3ActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Practica3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Practica3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Practica3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Practica3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Practica3().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton10;
    private javax.swing.JToggleButton jToggleButton11;
    private javax.swing.JToggleButton jToggleButton12;
    private javax.swing.JToggleButton jToggleButton13;
    private javax.swing.JToggleButton jToggleButton14;
    private javax.swing.JToggleButton jToggleButton15;
    private javax.swing.JToggleButton jToggleButton16;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton9;
    // End of variables declaration//GEN-END:variables
}